apiVersion: v1
kind: Template
metadata:
  name: mycloud
  annotations:
    description: "A simple Web application"
    iconClass: "icon-python"
    tags: "web"
objects:
- kind: "ImageStream"
  apiVersion: "v1"
  metadata:
    name: mycloud-webapp
    annotations:
      openshift.io/display-name: mycloud-webapp
  spec:
    tags:
    - name: latest
      annotations:
        iconClass: icon-python
      from:
        kind: DockerImage
        name: "quay.io/tkdchen/simplewebapp"
      importPolicy:
        scheduled: true
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: frontend-webapp
    labels:
      name: mycloud-webapp
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: mycloud-webapp
      spec:
        containers:
        - name: "mycloud-webapp"
          image: "mycloud-webapp:latest"
          ports:
          - containerPort: 5000
          resources:
            requests:
              cpu: "500m"
              memory: "64Mi"
    triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
        - "mycloud-webapp"
        from:
          kind: "ImageStreamTag"
          name: "mycloud-webapp:latest"
    strategy:
      type: Rolling
- apiVersion: v1
  kind: Service
  metadata:
    name: mycloud-webapp
  spec:
    selector:
      name: mycloud-webapp
    ports:
    - name: web
      port: 80
      targetPort: 5000
- apiVersion: v1
  kind: Route
  metadata:
    name: mycloud-route
  spec:
    to:
      kind: Service
      name: mycloud-webapp
