apiVersion: v1
kind: Template
metadata:
  name: mycloud
  annotations:
    description: "A simple Web application"
    iconClass: "icon-python"
    tags: "web"
objects:
- kind: "ImageStream"
  apiVersion: "v1"
  metadata:
    name: mycloud-webapp
    annotations:
      openshift.io/display-name: mycloud-webapp
  spec:
    tags:
    - name: latest
      annotations:
        iconClass: icon-python
      from:
        kind: DockerImage
        name: "quay.io/tkdchen/simplewebapp"
      importPolicy:
        scheduled: true
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    name: "frontend-webapp"
  spec:
    replicas: 2
    # selector:
    #   name: "frontend"
    template:
      metadata:
        labels:
          name: "mycloud-webapp"
      spec:
        containers:
        - name: "mycloud-webapp"
          image: "mycloud-webapp:latest"
          ports:
          - containerPort: 5000
            protocol: "TCP"
    triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
        - "mycloud-webapp"
        from:
          kind: "ImageStreamTag"
          name: "mycloud-webapp:latest"
    strategy:
      type: Rolling
# - kind: BuildConfig
#   apiVersion: v1
#   metadata:
#     name: mycloud
#     annotations:
#       description: A simple Web application running in the cloud
#   spec:
#     source:
#       type: Git
#       git:
#         uri: https://github.com/tkdchen/mycloud.git
#         ref: main
#     strategy:
#       sourceStrategy:
#         from:
#           kind: "ImageStreamTag"
#           name: "mycloud-webapp:latest"
#     triggers:
#     - type: "ConfigChange"
#     successfulBuildsHistoryLimit: 2
