apiVersion: v1
kind: Template
metadata:
  name: mycloud
  annotations:
    description: "A simple Web application"
    iconClass: "icon-python"
    tags: "web"
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: mycloud
    annotations:
      description: A simple Web application running in the cloud
      builds_count: 4
  spec:
    source:
      type: Git
      git:
        uri: https://github.com/tkdchen/mycloud.git
        ref: main
    strategy:
      dockerStrategy:
        dockerfilePath: Containerfile
    triggers:
    - type: "ConfigChange"
